package com.utilities.app.data

import android.content.Context
import com.utilities.app.keyboard.logic.WordBook
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

/**
 * The general dictionary, read off the disk once.
 *
 * Fifty thousand words is half a megabyte of asset, and reading it takes long enough that doing it
 * on the main thread would be a keyboard that takes a visible moment to appear the first time
 * somebody taps a text field. So it is read on the IO dispatcher and published when it lands: until
 * then the keyboard has [WordBook.EMPTY], which suggests nothing and corrects nothing, and the
 * household's own learned words — which are small and already loaded — carry the strip on their
 * own. Nothing waits for this, and nothing breaks if it never arrives.
 *
 * Unlike [LexiconStore] this holds nothing personal, is never written to, and is not in the backup:
 * it is the same file in every copy of the app, and a copy of it in somebody's archive would be
 * half a megabyte of English they can already get by reinstalling.
 */
class WordBookStore private constructor(context: Context) {

    private val assets = context.applicationContext.assets
    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    private val _words = MutableStateFlow(WordBook.EMPTY)
    val words: StateFlow<WordBook> = _words.asStateFlow()

    init {
        scope.launch {
            _words.value = runCatching {
                assets.open(ASSET_NAME).bufferedReader().useLines { WordBook.parse(it) }
            }.getOrDefault(WordBook.EMPTY)
        }
    }

    companion object {

        /** Generated by `utilities/tools/make-wordbook.sh`; see [WordBook] for what is in it. */
        const val ASSET_NAME = "wordbook-en.txt"

        @Volatile
        private var instance: WordBookStore? = null

        fun get(context: Context): WordBookStore =
            instance ?: synchronized(this) {
                instance ?: WordBookStore(context).also { instance = it }
            }
    }
}
