package com.utilities.app.keyboard

import com.utilities.app.keyboard.logic.Corrections
import com.utilities.app.keyboard.logic.Lexicon
import com.utilities.app.keyboard.logic.Vocabulary
import com.utilities.app.keyboard.logic.WordBook
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * The dictionary that actually ships, rather than one a test made up.
 *
 * It is generated by `utilities/tools/make-wordbook.sh` and committed, which means it is a file
 * somebody could regenerate with the wrong flags, hand-edit, or truncate on the way into a commit.
 * This reads the real thing off the disk and asks the four questions that would otherwise go
 * unnoticed until somebody's keyboard started behaving oddly: is it all there, is it in order, is
 * it *only* words, and does the licence notice it is distributed under still travel with it.
 *
 * The last few cases run the whole feature against it end to end — which is the only place in these
 * tests where `teh` becomes `the` for the same reason it will on a phone.
 */
class WordBookAssetTest {

    private val file: File = listOf(
        "src/main/assets/wordbook-en.txt",
        "utilities/src/main/assets/wordbook-en.txt"
    ).map(::File).firstOrNull { it.exists() }
        ?: throw AssertionError("the shipped dictionary is missing; run utilities/tools/make-wordbook.sh")

    private val lines: List<String> by lazy { file.readLines() }
    private val book: WordBook by lazy { WordBook.parse(lines.asSequence()) }

    @Test
    fun `it is all there`() {
        assertTrue("only ${book.size} words", book.size > 40_000)
        listOf("the", "keyboard", "don't", "receive", "separate", "hello", "dog's")
            .forEach { assertTrue("$it is missing", book.contains(it)) }
    }

    @Test
    fun `the commonest words are marked as the commonest`() {
        listOf("the", "and", "you", "because", "tomorrow").forEach {
            assertEquals("$it should be in the first tier", 1, book.tier(it))
        }
    }

    @Test
    fun `it is in the order the binary search needs, as written rather than as repaired`() {
        var previous = ""
        words().forEach { word ->
            assertTrue("'$previous' is followed by '$word'", word > previous)
            previous = word
        }
    }

    @Test
    fun `it is only words`() {
        words().forEach { word ->
            assertTrue("'$word' is not a word", word.all { it in 'a'..'z' || it == '\'' })
            assertTrue("'$word' starts or ends with an apostrophe", !word.startsWith("'") && !word.endsWith("'"))
            assertTrue("'$word' is too long to be one", word.length in 1..20)
        }
    }

    @Test
    fun `every word says how common it is`() {
        lines.filterNot { it.isEmpty() || it.startsWith("#") }.forEach { line ->
            assertTrue("'$line' has no tier", line[0] in '1'..'3')
        }
    }

    @Test
    fun `the copyright notice the licence asks for is still in the file`() {
        val header = lines.takeWhile { it.startsWith("#") || it.isEmpty() }.joinToString("\n")
        assertTrue("the SCOWL copyright notice has been dropped", header.contains("Kevin Atkinson"))
        assertTrue("the permission notice has been dropped", header.contains("Permission to use"))
    }

    @Test
    fun `there is nothing in it that a typo would be dragged towards`() {
        listOf("teh", "hte", "dont", "youre", "seperate", "recieve", "definately")
            .forEach { assertTrue("'$it' should not be a word", !book.contains(it)) }
    }

    // ---------------------------------------------------------------------------------------
    // The whole feature, against the real dictionary
    // ---------------------------------------------------------------------------------------

    private val english = Vocabulary(Lexicon.EMPTY, book)

    private fun correct(word: String, startsSentence: Boolean = false): String? =
        Corrections.of(word, startsSentence, english)?.to

    @Test
    fun `the typos everybody makes`() {
        mapOf(
            "teh" to "the",
            "hte" to "the",
            "thsi" to "this",
            "taht" to "that",
            "dont" to "don't",
            "youre" to "you're",
            "recieve" to "receive",
            "seperate" to "separate",
            "definately" to "definitely",
            "becuase" to "because",
            "tommorrow" to "tomorrow",
            "wrold" to "world",
            "helo" to "hello",
            "belive" to "believe",
            "occured" to "occurred",
            "keybaord" to "keyboard",
            "freind" to "friend",
            "adress" to "address"
        ).forEach { (typed, expected) -> assertEquals(expected, correct(typed)) }
    }

    @Test
    fun `and the words a keyboard has no business touching`() {
        // Not a word, but nothing near it is either.
        assertNull(correct("asdfgh"))
        // `a lot` is two words and this corrects one, so `alot` is left alone rather than made into
        // `alto` or `slot`, neither of which is what anybody meant.
        assertNull(correct("alot"))
        // A name, at the start of a sentence, one far-away letter from `Add`.
        assertNull(correct("Ada", startsSentence = true))
        assertNull(correct("Wetherby", startsSentence = true))
        // Acronyms, which are not words and are not typos either.
        listOf("NASA", "NHS", "USB", "OMG", "LOL", "ASAP").forEach {
            assertNull("$it was corrected", correct(it, startsSentence = true))
        }
    }

    @Test
    fun `a word this household types is never corrected, even the first time`() {
        val mine = Vocabulary(Lexicon.EMPTY.learn("lifeops"), book)
        assertNull(Corrections.of("lifeops", false, mine))
    }

    /** Every word in the file, in the order it is written in. */
    private fun words(): Sequence<String> =
        lines.asSequence().filterNot { it.isEmpty() || it.startsWith("#") }.map { it.substring(1) }
}
